M7R0
I1genSchurPolyList7iem"""""#""$,&%"mGF$!"#F$,&F(F$!""F$F(,&F(F$F$F$,&F(F$F%F$,&
F(F$F&F$,&F(F%!"&F$,&F(F%!"%F$,&F(F%!"$F$,&F(F%F)F$,&F(F%F+F$,$F(F%,&F(F%F$F$,&
F(F%F%F$,&F(F&!"(F$,&F(F%F&F$,&F(F&!"'F$,&F0F$F(F&,&F2F$F(F&,&F4F$F(F&,&F(F&F)F
$,&F(F&F+F$,$F(F&,&F(""%!"*F$,&F(F&F$F$,&F(FF!")F$,&F(FFF;F$,&F(FFF>F$,&F(FFF0F
$,&F(FFF2F$,&F(FFF4F$,&F(FFF)F$,&F(FFF+F$,&F(""&FGF$,&F(FSFJF$,&F(FSF;F$,&F(FSF
>F$,&F(FSF0F$,&F(FSF2F$,&F(FSF4F$z)6#F(#F$"F0!""(z)Fen#F$"F0!"")z)Fen#F$"F0!""*
z)Fen#F$"F2!FFz)Fen#F$"F2!FSz)Fen#F$"F2!""'z)Fen#F$"F2!Ffnz)Fen#F$"F2!Fhnz)Fen#
F$"F2!Fjnz)Fen#F$"F4!F$Fboz)Fen#F$"F4!F%z)Fen#F$"F4!F&z)Fen#F$"F4!FFz)Fen#F$"F4
!FSz)Fen#F$"F4!F^oz)Fen#F$"F4!Ffnz)Fen#F$"F4!Fhnz)Fen#F$"F)!F)z)Fen#F$"F4!Fjnz)
Fen#F$"F)!F+z'Fen#F$"F)F]pz)Fen#F$"F)!F$F^pz)Fen#F$"F)!F%z)Fen#F$"F)!F&z)Fen#F$
"F)!FFz)Fen#F$"F+!F0z)Fen#F$"F)!FSz)Fen#F$"F+!F2z)Fen#F$"F)!F^oz)Fen#F$"F+!F4z)
Fen#F$"F)!Ffnz)Fen#F$"F+!F)z)Fen#F$"F+!F+z'Fen#F$"F+z)Fen#F$"F+!F$z)Fen#F$"F+!F
%z'Fen#F$!FJz)Fen#F$"F+!F&z'Fen#F$!F;z)Fen#F$"F+!FFz'Fen#F$!F>z)Fen#F$"F+!FSz'F
en#F$!F0z'Fen#F$!F2z'Fen#F$!F4z'Fen#F$!F)z'Fen#F$!F+*$F(F%z)Fen#F$"F$!FGz'Fen#F
$!F$z)Fen#F$"F$!FJz'Fen#F$!F%z)Fen#F$"F$!F;z'Fen#F$!F&z)Fen#F$"F$!F>z)Fen#F$"F$
!F0z)Fen#F$"F$!F2z)Fen#F$"F$!F4z)Fen#F$"F$!F)z)Fen#F$"F$!F+z'Fen#F$"F$z)Fen#F$"
F%!FGz)Fen#F$"F$!F$z)Fen#F$"F%!FJz)Fen#F$"F%!F;z)Fen#F$"F%!F>z)Fen#F$"F%!F0z)Fe
n#F$"F%!F2z)Fen#F$"F%!F4z)Fen#F$"F%!F)z)Fen#F$"F%!F+z)Fen#F$"F&!FGz)Fen#F$"F%!F
$z)Fen#F$"F&!FJz)Fen#F$"F&!F;z)Fen#F$"F&!F>z)Fen#F$"F&!F0z)Fen#F$"F&!F2z)Fen#F%
"FJ!Ffnz)Fen#F$"F&!F4z)Fen#F%"FJ!Fhnz)Fen#F$"F&!F+z)Fen#F$"FF!F;z)Fen#F%"F;!FFz
)Fen#F$"FF!F>z)Fen#F%"F;!FSz)Fen#F$"FF!F0z)Fen#F%"F;!F^oz)Fen#F%"F;!Ffnz)Fen#F$
"FF!F4z)Fen#F%"F;!Fhnz)Fen#F%"F;!Fjnz)Fen#F%"F>!F$z)Fen#F%"F>!F%z)Fen#F%"F>!F&z
)Fen#F%"F>!FFz)Fen#F%"F>!FSz)Fen#F$"FS!F0z)Fen#F%"F>!F^oz)Fen#F%"F>!Ffnz)Fen#F%
"F0!F)z)Fen#F%"F>!Fhnz)Fen#F%"F0!F+z)Fen#F%"F>!Fjnz'Fen#F%"F0z)Fen#F%"F0!F$z)Fe
n#F%"F0!F%z)Fen#F%"F0!F&z)Fen#F%"F0!FFz)Fen#F%"F2!F0z)Fen#F%"F0!FSz)Fen#F%"F2!F
2z)Fen#F%"F0!F^oz)Fen#F%"F2!F4z)Fen#F%"F0!Ffnz)Fen#F%"F2!F)z)Fen#F%"F0!Fhnz)Fen
#F%"F2!F+z)Fen#F%"F0!Fjnz'Fen#F%"F2z)Fen#F%"F2!F$z)Fen#F%"F2!F%z)Fen#F%"F4!F;z)
Fen#F%"F2!F&z)Fen#F%"F4!F>z)Fen#F%"F2!FFz)Fen#F%"F4!F0z)Fen#F%"F2!FSz)Fen#F%"F4
!F2z)Fen#F%"F2!F^oz)Fen#F%"F4!F4z)Fen#F%"F2!Ffnz)Fen#F%"F4!F)z)Fen#F%"F4!F+z'Fe
n#F%"F4z)Fen#F%"F)!FGz)Fen#F%"F4!F$z)Fen#F%"F)!FJz)Fen#F%"F4!F%z)Fen#F%"F)!F;z)
Fen#F%"F4!F&z)Fen#F%"F)!F>z)Fen#F%"F4!FFz)Fen#F%"F)!F0z)Fen#F%"F4!FSz)Fen#F%"F)
!F2z)Fen#F%"F)!F4z)Fen#F%"F4!Ffnz)Fen#F%"F)!F)z)Fen#F%"F)!F+z'Fen#F%"F)z)Fen#F%
"F+!FGz)Fen#F%"F)!F$z)Fen#F%"F+!FJz)Fen#F%"F)!F%z)Fen#F%"F+!F;z)Fen#F%"F)!F&z)F
en#F%"F+!F>z)Fen#F%"F+!F0z)Fen#F%"F)!FSz)Fen#F%"F+!F2z)Fen#F%"F+!F4z)Fen#F%"F+!
F)z)Fen#F%"F+!F+z'Fen#F%"F+z)Fen#F%"F+!F$z'Fen#F%!FGz'Fen#F%!FJz)Fen#F%"F+!F&z'
Fen#F%!F;z'Fen#F%!F>z'Fen#F%!F0z'Fen#F%!F2z'Fen#F%!F4z'Fen#F%!F)z'Fen#F%!F+,$Fh
qF%z)Fen#F%"F$!FGz'Fen#F%!F$z)Fen#F%"F$!FJz)Fen#F%"F$!F;z)Fen#F&"!#5!FFz)Fen#F%
"F$!F>z)Fen#F&"F_z!FSz)Fen#F%"F$!F0z)Fen#F&"F_z!F^oz)Fen#F%"F$!F2z)Fen#F&"F_z!F
fnz)Fen#F%"F$!F4z)Fen#F&"F_z!Fhnz)Fen#F%"F$!F)z)Fen#F%"F$!F+z)Fen#F&"FG!F$z)Fen
#F&"FG!F%z)Fen#F&"FG!F&z)Fen#F%"F%!F;z)Fen#F&"FG!FFz)Fen#F%"F%!F>z)Fen#F&"FG!FS
z)Fen#F%"F%!F0z)Fen#F&"FG!F^oz)Fen#F%"F%!F2z)Fen#F&"FG!Ffnz)Fen#F%"F%!F4z)Fen#F
&"FG!Fhnz)Fen#F&"FJ!F+z'Fen#F&"FJz)Fen#F&"FJ!F$z)Fen#F&"FJ!F%z)Fen#F&"FJ!F&z)Fe
n#F&"FJ!FFz)Fen#F%"F&!F>z)Fen#F&"FJ!FSz)Fen#F%"F&!F0z)Fen#F&"FJ!F^oz)Fen#F&"F;!
F4z)Fen#F&"FJ!Ffnz)Fen#F&"F;!F)z)Fen#F&"F;!F+z'Fen#F&"F;z)Fen#F&"F;!F$z)Fen#F&"
F;!F%z)Fen#F&"F;!F&z)Fen#F&"F;!FFz)Fen#F&"F>!F0z)Fen#F&"F;!FSz)Fen#F&"F>!F2z)Fe
n#F&"F;!F^oz)Fen#F&"F>!F4z)Fen#F&"F;!Ffnz)Fen#F&"F>!F)z)Fen#F&"F>!F+z'Fen#F&"F>
z)Fen#F&"F>!F$z)Fen#F&"F>!F%z)Fen#F&"F0!F;z)Fen#F&"F>!F&z)Fen#F&"F0!F>z)Fen#F&"
F>!FFz)Fen#F&"F0!F0z)Fen#F&"F>!FSz)Fen#F&"F0!F2z)Fen#F&"F>!F^oz)Fen#F&"F0!F4z)F
en#F&"F>!Ffnz)Fen#F&"F0!F)z)Fen#F&"F0!F+z'Fen#F&"F0z)Fen#F&"F2!FGz)Fen#F&"F0!F$
z)Fen#F&"F2!FJz)Fen#F&"F0!F%z)Fen#F&"F2!F;z)Fen#F&"F0!F&z)Fen#F&"F2!F>z)Fen#F&"
F0!FFz)Fen#F&"F2!F0z)Fen#F&"F0!FSz)Fen#F&"F2!F2z)Fen#F&"F0!F^oz)Fen#F&"F2!F4z)F
en#F&"F0!Ffnz)Fen#F&"F2!F)z)Fen#F&"F2!F+z'Fen#F&"F2z)Fen#F&"F4!FGz)Fen#F&"F2!F$
z)Fen#F&"F4!FJz)Fen#F&"F2!F%z)Fen#F&"F4!F;z)Fen#F&"F2!F&z)Fen#F&"F4!F>z)Fen#F&"
F2!FFz)Fen#F&"F4!F0z)Fen#F&"F2!FSz)Fen#F&"F4!F2z)Fen#F&"F4!F4z)Fen#F&"F4!F)z)Fe
n#F&"F4!F+z'Fen#F&"F4z)Fen#F&"F4!F$z)Fen#F&"F4!F%z)Fen#F&"F)!F;z)Fen#F&"F4!F&z)
Fen#F&"F)!F>z)Fen#F&"F)!F0z)Fen#F&"F)!F2z)Fen#F&"F)!F4z)Fen#F&"F)!F)z)Fen#F&"F)
!F+z'Fen#F&"F)z)Fen#F&"F)!F$z)Fen#F&"F+!F;z)Fen#F&"F+!F>z)Fen#F&"F+!F0z)Fen#F&"
F+!F2z)Fen#F&"F+!F4z)Fen#F&"F+!F)z)Fen#F&"F+!F+z'Fen#F&!F;z'Fen#F&!F>z'Fen#F&!F
0z'Fen#F&!F2z'Fen#F&!F4z)Fen#F&"F$!F>z)Fen#F&"F$!F0z)Fen#FF"FG!F^oz)Fen#FF"FJ!F
Fz)Fen#FF"F;!F%z)Fen#FF"F;!F^oz'Fen#FF"F>z)Fen#FF"F>!FFz)Fen#FF"F0!F)z)Fen#FF"F
0!F%z)Fen#FF"F2!F2z'Fen#FF"F2z)Fen#FF"F4!F>z)Fen#FF"F4!F)z)Fen#FF"F)!F2z)Fen#FF
"F+!F>z+Fen$F$#F0"FF!Ffnz+Fen$F$#F0"FF!Fhnz+Fen$F$#F0"FF!Fjnz+Fen$F$#F0"FS!FFz+
Fen$F$#F0"FS!FSz+Fen$F$#F0"FS!F^oz+Fen$F$#F0"FS!Ffnz+Fen$F$#F0"FS!Fhnz+Fen$F$#F
0"FS!Fjnz+Fen$F$#F0"F^o!F$z+Fen$F$#F0"F^o!F%z+Fen$F$#F0"F^o!F&z+Fen$F$#F0"F^o!F
Fz+Fen$F$#F0"F^o!FSz+Fen$F$#F0"F^o!F^oz+Fen$F$#F0"F^o!Ffnz+Fen$F$#F0"Ffn!F)z+Fe
n$F$#F0"Ffn!F+z)Fen$F$#F0"Ffnz+Fen$F$#F0"Ffn!F$z+Fen$F$#F0"Ffn!F%z+Fen$F$#F0"Ff
n!F&z+Fen$F$#F0"Ffn!FFz+Fen$F$#F0"Fhn!F0z+Fen$F$#F0"Ffn!FSz+Fen$F$#F0"Fhn!F2z+F
en$F$#F0"Fhn!F4z+Fen$F$#F0"Fhn!F)z+Fen$F$#F0"Fhn!F+z)Fen$F$#F0"Fhnz+Fen$F$#F0"F
hn!F$z+Fen$F$#F0"Fhn!F%z+Fen$F$#F0"Fjn!F;z+Fen$F$#F0"Fhn!F&z+Fen$F$#F0"Fjn!F>z+
Fen$F$#F0"Fjn!F0z+Fen$F$#F0"Fjn!F2z+Fen$F$#F0"Fjn!F4z+Fen$F$#F0"Fjn!F)z+Fen$F$#
F0"Fjn!F+z)Fen$F$#F0"Fjnz+Fen$F$#F0"Fjn!F$z+Fen$F$#F0""#5!F;z+Fen$F$#F0"Feel!F>
z+Fen$F$#F0"Feel!F0z+Fen$F$#F0"Feel!F2z+Fen$F$#F0"Feel!F4z+Fen$F$#F0"Feel!F)z+F
en$F$#F0"Feel!F+z+Fen$F$#F2"F$!Ffnz+Fen$F$#F2"F$!Fhnz+Fen$F$#F2"F$!Fjnz+Fen$F$#
F2"F%!FFz+Fen$F$#F2"F%!FSz+Fen$F$#F2"F%!F^oz+Fen$F$#F2"F%!Ffnz+Fen$F$#F2"F%!Fhn
z+Fen$F$#F2"F%!Fjnz+Fen$F$#F2"F&!F$z+Fen$F$#F2"F&!F%z+Fen$F$#F2"F&!F&z+Fen$F$#F
2"F&!FFz+Fen$F$#F2"F&!FSz+Fen$F$#F2"F&!F^oz+Fen$F$#F2"F&!Ffnz+Fen$F$#F2"FF!F)z+
Fen$F$#F2"F&!Fhnz+Fen$F$#F2"FF!F+z+Fen$F$#F2"F&!Fjnz)Fen$F$#F2"FFz+Fen$F$#F2"FF
!F$z+Fen$F$#F2"FF!F%z+Fen$F$#F2"FF!F&z+Fen$F$#F2"FF!FFz+Fen$F$#F2"FS!F0z+Fen$F$
#F2"FF!FSz+Fen$F$#F2"FS!F2z+Fen$F$#F2"FF!F^oz+Fen$F$#F2"FS!F4z+Fen$F$#F2"FF!Ffn
z+Fen$F$#F2"FS!F)z+Fen$F$#F2"FS!F+z)Fen$F$#F2"FSz+Fen$F$#F2"FS!F$z+Fen$F$#F2"FS
!F%z+Fen$F$#F2"F^o!F;z+Fen$F$#F2"FS!F&z+Fen$F$#F2"F^o!F>z+Fen$F$#F2"FS!FFz+Fen$
F$#F2"F^o!F0z+Fen$F$#F2"FS!FSz+Fen$F$#F2"F^o!F2z+Fen$F$#F2"F^o!F4z+Fen$F$#F2"FS
!Ffnz+Fen$F$#F2"F^o!F)z+Fen$F$#F2"F^o!F+z)Fen$F$#F2"F^oz+Fen$F$#F2"F^o!F$z+Fen$
F$#F2"F^o!F%z+Fen$F$#F2"Ffn!F;z+Fen$F$#F2"F^o!F&z+Fen$F$#F2"Ffn!F>z+Fen$F$#F2"F
fn!F0z+Fen$F$#F2"F^o!FSz+Fen$F$#F2"Ffn!F2z+Fen$F$#F2"Ffn!F4z+Fen$F$#F2"Ffn!F)z+
Fen$F$#F2"Ffn!F+z)Fen$F$#F2"Ffnz+Fen$F$#F2"Ffn!F$z+Fen$F$#F2"Fhn!F;z+Fen$F$#F2"
Ffn!F&z+Fen$F$#F2"Fhn!F>z+Fen$F$#F2"Fhn!F0z+Fen$F$#F2"Fhn!F2z+Fen$F$#F2"Fhn!F4z
+Fen$F$#F2"Fhn!F)z+Fen$F$#F2"Fhn!F+z+Fen$F$#F2"Fhn!F$z+Fen$F$#F2"Fjn!F0z+Fen$F$
#F2"Fjn!F2z+Fen$F$#F4"F)!Ffnz+Fen$F$#F2"Fjn!F4z+Fen$F$#F4"F)!Fhnz+Fen$F$#F2"Fjn
!F+z+Fen$F$#F4"F+!FFz+Fen$F$#F4"F+!FSz+Fen$F$#F4"F+!F^oz+Fen$F$#F4"F+!Ffnz+Fen$
F$#F2"Feel!F4z+Fen$F$#F4"F+!Fhnz)Fen$F$#F4!F$z)Fen$F$#F4!F%z)Fen$F$#F4!F&z)Fen$
F$#F4!FFz)Fen$F$#F4!FSz)Fen$F$#F4!F^oz)Fen$F$#F4!Ffnz+Fen$F$#F4"F$!F)z+Fen$F$#F
4"F$!F+z)Fen$F$#F4"F$z+Fen$F$#F4"F$!F$z+Fen$F$#F4"F$!F%z+Fen$F$#F4"F$!F&z+Fen$F
$#F4"F$!FFz+Fen$F$#F4"F%!F0z+Fen$F$#F4"F$!FSz+Fen$F$#F4"F%!F2z+Fen$F$#F4"F$!F^o
z+Fen$F$#F4"F%!F4z+Fen$F$#F4"F$!Ffnz+Fen$F$#F4"F%!F)z+Fen$F$#F4"F%!F+z)Fen$F$#F
4"F%z+Fen$F$#F4"F%!F$z+Fen$F$#F4"F%!F%z+Fen$F$#F4"F&!F;z+Fen$F$#F4"F%!F&z+Fen$F
$#F4"F&!F>z+Fen$F$#F4"F%!FFz+Fen$F$#F4"F&!F0z+Fen$F$#F4"F%!FSz+Fen$F$#F4"F&!F2z
+Fen$F$#F4"F%!F^oz+Fen$F$#F4"F&!F4z+Fen$F$#F4"F%!Ffnz+Fen$F$#F4"F&!F)z+Fen$F$#F
4"F&!F+z)Fen$F$#F4"F&z+Fen$F$#F4"F&!F$z+Fen$F$#F4"F&!F%z+Fen$F$#F4"FF!F;z+Fen$F
$#F4"F&!F&z+Fen$F$#F4"FF!F>z+Fen$F$#F4"F&!FFz+Fen$F$#F4"FF!F0z+Fen$F$#F4"F&!FSz
+Fen$F$#F4"FF!F2z+Fen$F$#F4"F&!F^oz+Fen$F$#F4"FF!F4z+Fen$F$#F4"F&!Ffnz+Fen$F$#F
4"FF!F)z+Fen$F$#F4"FF!F+z)Fen$F$#F4"FFz+Fen$F$#F4"FF!F$z+Fen$F$#F4"FF!F%z+Fen$F
$#F4"FF!F&z+Fen$F$#F4"FF!FFz+Fen$F$#F4"FS!F0z+Fen$F$#F4"FF!FSz+Fen$F$#F4"FS!F2z
+Fen$F$#F4"FS!F4z+Fen$F$#F4"FS!F)z+Fen$F$#F4"FS!F+z)Fen$F$#F4"FSz+Fen$F$#F4"FS!
F$z+Fen$F$#F4"FS!F%z+Fen$F$#F4"FS!F&z+Fen$F$#F4"F^o!F0z+Fen$F$#F4"F^o!F2z+Fen$F
$#F4"F^o!F4z+Fen$F$#F4"F^o!F)z+Fen$F$#F4"F^o!F+z)Fen$F$#F4"F^oz+Fen$F$#F4"F^o!F
$z+Fen$F$#F)"F2!FFz+Fen$F$#F4"Ffn!F0z+Fen$F$#F4"Ffn!F2z+Fen$F$#F4"Ffn!F4z+Fen$F
$#F4"Ffn!F)z+Fen$F$#F4"Ffn!F+z+Fen$F$#F)"F4!F%z+Fen$F$#F4"Fhn!F2z+Fen$F$#F4"Fhn
!F4z+Fen$F$#F)"F)!F+z)Fen$F$#F)"F)z+Fen$F$#F)"F)!F$z+Fen$F$#F)"F)!F%z+Fen$F$#F)
"F)!F&z+Fen$F$#F)"F)!FFz+Fen$F$#F)"F+!F4z+Fen$F$#F)"F+!F)z+Fen$F$#F)"F+!F+z)Fen
$F$#F)"F+z+Fen$F$#F)"F+!F$z+Fen$F$#F)"F+!F%z+Fen$F$#F)"F+!F&z+Fen$F$#F)"F+!FFz+
Fen$F$#F)"F+!FSz)Fen$F$#F)!F0z+Fen$F$#F)"F+!F^oz)Fen$F$#F)!F2z)Fen$F$#F)!F4z)Fe
n$F$#F)!F)z)Fen$F$#F)!F+z'Fen$F$#F)z)Fen$F$#F)!F$z)Fen$F$#F)!F%z)Fen$F$#F)!F&z+
Fen$F$#F)"F$!F>z)Fen$F$#F)!FFz+Fen$F$#F)"F$!F0z)Fen$F$#F)!FSz+Fen$F$#F)"F$!F2z+
Fen$F$#F)"F$!F4z+Fen$F$#F)"F$!F)z+Fen$F$#F)"F$!F+z)Fen$F$#F)"F$z+Fen$F$#F)"F$!F
$z+Fen$F$#F)"F$!F%z+Fen$F$#F)"F$!F&z+Fen$F$#F)"F$!FFz+Fen$F$#F)"F%!F0z+Fen$F$#F
)"F$!FSz+Fen$F$#F)"F%!F2z+Fen$F$#F)"F$!F^oz+Fen$F$#F)"F%!F4z+Fen$F$#F)"F%!F)z+F
en$F$#F)"F%!F+z)Fen$F$#F)"F%z+Fen$F$#F)"F%!F$z+Fen$F$#F)"F%!F%z+Fen$F$#F)"F%!F&
z+Fen$F$#F)"F%!FFz+Fen$F$#F)"F&!F0z+Fen$F$#F)"F&!F2z+Fen$F$#F)"F&!F4z+Fen$F$#F)
"F&!F)z+Fen$F$#F)"F&!F+z)Fen$F$#F)"F&z+Fen$F$#F)"F&!F$z+Fen$F$#F)"F&!F%z+Fen$F$
#F)"F&!F&z+Fen$F$#F)"FF!F>z+Fen$F$#F+"F;!F^oz+Fen$F$#F)"FF!F2z+Fen$F$#F)"FF!F4z
+Fen$F$#F)"FF!F)z+Fen$F$#F)"FF!F+z)Fen$F$#F)"FFz+Fen$F$#F)"FF!F$z+Fen$F$#F+"F>!
FFz+Fen$F$#F)"FS!F)z+Fen$F$#F)"FS!F+z+Fen$F$#F+"F0!F%z+Fen$F$#F)"F^o!F2z+Fen$F$
#F+"F2!F+z)Fen$F$#F+"F2z+Fen$F$#F+"F2!F$z+Fen$F$#F+"F2!F%z+Fen$F$#F+"F2!F&z+Fen
$F$#F+"F2!FFz+Fen$F$#F+"F2!F^oz+Fen$F$#F+"F4!F4z+Fen$F$#F+"F4!F)z+Fen$F$#F+"F4!
F+z)Fen$F$#F+"F4z+Fen$F$#F+"F4!F$z+Fen$F$#F+"F4!F%z+Fen$F$#F+"F4!F&z+Fen$F$#F+"
F4!FFz+Fen$F$#F+"F)!F0z+Fen$F$#F+"F4!FSz+Fen$F$#F+"F)!F2z+Fen$F$#F+"F)!F4z+Fen$
F$#F+"F)!F)z+Fen$F$#F+"F)!F+z)Fen$F$#F+"F)z+Fen$F$#F+"F)!F$z+Fen$F$#F+"F)!F%z+F
en$F$#F+"F)!F&z+Fen$F$#F+"F+!F>z+Fen$F$#F+"F)!FFz+Fen$F$#F+"F+!F0z+Fen$F$#F+"F)
!FSz+Fen$F$#F+"F+!F2z+Fen$F$#F+"F+!F4z+Fen$F$#F+"F+!F)z+Fen$F$#F+"F+!F+6"
