
#include <iostream>
#include <string>
#include <vector>
#include <sstream>
#include <stdlib.h>
#include <fstream>

std::string SCIP_file = "tempSCIPsols.txt";

std::string generate_file_name(std::string A, int k, int n){
    // assume equation in the form of [1,1,-1], k = 2, n = 4
    // we want "rado_1_1_-1_k2_n4.cnf"

    std::string equation = A.substr(1, A.length()-2);
    std::string file_name = "rado_";

    std::stringstream ss(equation);
    while(ss.good()){
        std::string value;
        std::getline(ss, value, ',');
        file_name = file_name + value + "_";
    }
    file_name = file_name + "k" + std::to_string(k) + "_n" + std::to_string(n)\
    + ".cnf"; 
    return file_name;
}

std::string generate_negative_clause(std::vector<int> solution, int k){

    // for solution 2 1 1 -> 2 = 1 + 1
    // for each color, there would be -z -x -y

    std::string clauses = "";
    std::string subclause = "";
    for(int c = (k-1); c >= 0; c--){
        std::string subclause;
        for(int index = 0; index < solution.size(); index++){
            subclause = subclause + "-" +\
            std::to_string((solution[index]*k)-c) + " ";
        }
        subclause = subclause + "0 \n";
        clauses = clauses + subclause;
    }

    return clauses;
}

void prepare_parameter_line(int num_literal, int num_clauses, std::string file_name){
    std::ofstream file(file_name, std::ofstream::trunc);
    file << "p cnf " + std::to_string(num_literal) + " " + std::to_string(num_clauses)\
    + "\n";
    file.close();
}

int write_positive_clauses(std::string file_name, int k, int n){

    std::ofstream file(file_name, std::ofstream::trunc);
    int index = 1;
    int count = 0;
    int i,j;
    for(i = 1; i <= n; i++){
        for(j = 1; j <= k; j++){
            file << std::to_string(index++) + " ";
        }
        file << "0 \n";
        count++;
    }
    file.close();
    return count;
}

int write_negative_clauses(std::string file_name, int k){
    int count = 0;
    std::ifstream SCIP(SCIP_file);
    std::ofstream file(file_name, std::ofstream::app);
    if(!SCIP){
        std::cerr << "Cannot open SCIP file" << std::endl;
        exit(1);
    }
    std::string line;
    // skip first line
    std::getline(SCIP, line);
    while(std::getline(SCIP, line)){
        // remove end ", 0"
        line = line.substr(0,line.length()-3);
        std::vector<int> solution;
        std::stringstream ss(line);
        std::string value;
        std::getline(ss, value, ',');
        while(ss.good()){
            std::getline(ss, value, ',');
            solution.emplace_back(std::stoi(value));
        }
        file << generate_negative_clause(solution, k);
        count++;
    }

    // close the files
    SCIP.close();
    file.close();
    return count * k;
}

int write_optional_clauses(std::string file_name, int k, int n){

    std::ofstream file(file_name, std::ofstream::app);
    int count = 0;
    int i,j,q;
    for(i = 1; i <= n; i++){

        for(j = 1; j <= k-1; j++){

            for(q = j+1; q <= k; q++){
                file << "-"+std::to_string(i*k-(k-j)) + " "\
                + "-"+std::to_string(i*k-(k-q)) + " 0 \n";
                count++;
            }
        }
    }
    file.close();
    return count;
}


int main(int argc, char **argv){

    // k for number of colours, n for range [1,n]
    int k,n;
    std::string A; 
    std::string file_name;
    int num_clauses = 0;
    // the equation would be generated by SCIP and read here


    if(argc == 1 || argc != 4){ 
        std::cout << "RadoCG: k n A" << std::endl;
        return 1;
    }else{
        k = std::atoi(argv[1]);
        n = std::atoi(argv[2]);
        A = std::string(argv[3]);
    }

    file_name = generate_file_name(A,k,n);
    num_clauses = num_clauses + write_positive_clauses("temp.txt", k, n);
    num_clauses = num_clauses + write_negative_clauses("temp.txt", k);
    num_clauses = num_clauses + write_optional_clauses("temp.txt", k, n);
    prepare_parameter_line(n*k, num_clauses, file_name);

    return 0;
}